trigger:
- main

jobs:
- job: CheckBrowsers
  pool:
    vmImage: 'windows-latest'  # Change to 'ubuntu-latest' for Linux agents

  steps:
  - powershell: |
      Write-Host "Checking for available web browsers..."

      # Windows browsers
      $browsers = @()
      $browsers += if (Get-Command "chrome" -ErrorAction SilentlyContinue) { "Google Chrome" }
      $browsers += if (Get-Command "msedge" -ErrorAction SilentlyContinue) { "Microsoft Edge" }
      $browsers += if (Get-Command "firefox" -ErrorAction SilentlyContinue) { "Mozilla Firefox" }

      if ($browsers.Count -eq 0) {
          Write-Host "No web browsers found."
          exit 1
      } else {
          Write-Host "Available web browsers: $($browsers -join ', ')"
      }
    displayName: 'Check available web browsers (Windows)'

  - script: |
      echo "Checking for available web browsers..."

      # Linux browsers
      browsers=()
      if command -v google-chrome >/dev/null; then browsers+=("Google Chrome"); fi
      if command -v chromium-browser >/dev/null; then browsers+=("Chromium"); fi
      if command -v firefox >/dev/null; then browsers+=("Mozilla Firefox"); fi
      if command -v brave-browser >/dev/null; then browsers+=("Brave"); fi
      if command -v opera >/dev/null; then browsers+=("Opera"); fi

      if [ ${#browsers[@]} -eq 0 ]; then
          echo "No web browsers found."
          exit 1
      else
          echo "Available web browsers: ${browsers[*]}"
      fi
    displayName: 'Check available web browsers (Linux)'
    condition: eq( variables['Agent.OS'], 'Linux' )
