trigger:
- main

jobs:
- job: CheckBrowsers
  pool: Default

  steps:
  - powershell: |
      Write-Host "Checking for available web browsers..."

      # Initialize an array to hold the names of found browsers
      $browsers = @()

      # Check for common browser executables
      $browserPaths = @(
          "C:\Program Files\Google\Chrome\Application\chrome.exe",
          "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
          "C:\Program Files\Mozilla Firefox\firefox.exe"
      )

      foreach ($path in $browserPaths) {
          if (Test-Path $path) {
              $browsers += [System.IO.Path]::GetFileNameWithoutExtension($path)
          }
      }

      if ($browsers.Count -eq 0) {
          Write-Host "No web browsers found."
          exit 1
      } else {
          Write-Host "Available web browsers: $($browsers -join ', ')"
      }
    displayName: 'Check available web browsers (Windows 11)'
